[package]
name = "swl-viewer"
version = "0.1.0"
edition = "2021"


[dependencies]
eframe = "0.27"
egui   = "0.27"
regex  = "1"
chrono = { version = "0.4", default-features = false, features = ["clock"], optional = true }
rfd = "0.14"
home = "=0.5.11"
